#!/usr/bin/env python3
"""Audit a translated PDF image package."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path, help="Manifest generated by prepare_pdf_pages.py")
    parser.add_argument("--translated-dir", required=True, type=Path, help="Directory containing translated page images")
    parser.add_argument("--translated-pdf", "--pdf", dest="translated_pdf", type=Path, help="Translated-only PDF to check")
    parser.add_argument("--bilingual-pdf", type=Path, help="Bilingual comparison PDF to check")
    parser.add_argument("--comparison-gap", type=int, default=24, help="Gap in pixels used by the bilingual comparison PDF")
    parser.add_argument("--dimension-tolerance-px", type=int, default=8)
    return parser.parse_args()


def pdf_page_count(path: Path) -> int | None:
    try:
        from pypdf import PdfReader  # type: ignore
    except Exception:
        return None
    return len(PdfReader(str(path)).pages)


def pdf_page_sizes(path: Path) -> list[tuple[float, float]] | None:
    try:
        from pypdf import PdfReader  # type: ignore
    except Exception:
        return None
    reader = PdfReader(str(path))
    return [(float(page.mediabox.width), float(page.mediabox.height)) for page in reader.pages]


def main() -> int:
    args = parse_args()
    manifest_path = args.manifest.expanduser().resolve()
    translated_dir = args.translated_dir.expanduser().resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    pages = manifest.get("pages", [])
    errors: list[str] = []
    warnings: list[str] = []

    if not translated_dir.exists():
        errors.append(f"Translated image directory missing: {translated_dir}")
    else:
        for page in pages:
            page_number = int(page["page_number"])
            image_path = translated_dir / f"page-{page_number:03d}.png"
            if not image_path.exists():
                matches = sorted(translated_dir.glob(f"page-{page_number:03d}.*"))
                if not matches:
                    errors.append(f"Missing translated image for page {page_number}")
                    continue
                image_path = matches[0]
            with Image.open(image_path) as image:
                expected = (int(page["render_width_px"]), int(page["render_height_px"]))
                actual = image.size
                if (
                    abs(actual[0] - expected[0]) > args.dimension_tolerance_px
                    or abs(actual[1] - expected[1]) > args.dimension_tolerance_px
                ):
                    warnings.append(f"Page {page_number} image dimensions {actual} differ from expected {expected}")

    translated_pdf_count = None
    bilingual_pdf_count = None
    translated_pdf_sizes = None
    bilingual_pdf_sizes = None

    if args.translated_pdf:
        pdf_path = args.translated_pdf.expanduser().resolve()
        if not pdf_path.exists():
            errors.append(f"Translated PDF missing: {pdf_path}")
        else:
            translated_pdf_count = pdf_page_count(pdf_path)
            translated_pdf_sizes = pdf_page_sizes(pdf_path)
            if translated_pdf_count is not None and translated_pdf_count != len(pages):
                errors.append(f"Translated PDF has {translated_pdf_count} pages; expected {len(pages)}")
            elif translated_pdf_count is None:
                warnings.append("Could not verify translated PDF page count because pypdf is unavailable")

    if args.bilingual_pdf:
        pdf_path = args.bilingual_pdf.expanduser().resolve()
        if not pdf_path.exists():
            errors.append(f"Bilingual PDF missing: {pdf_path}")
        else:
            bilingual_pdf_count = pdf_page_count(pdf_path)
            bilingual_pdf_sizes = pdf_page_sizes(pdf_path)
            if bilingual_pdf_count is not None and bilingual_pdf_count != len(pages):
                errors.append(f"Bilingual PDF has {bilingual_pdf_count} pages; expected {len(pages)}")
            elif bilingual_pdf_count is None:
                warnings.append("Could not verify bilingual PDF page count because pypdf is unavailable")

    if bilingual_pdf_sizes is not None:
        for idx, page in enumerate(pages):
            if idx >= len(bilingual_pdf_sizes):
                break
            expected_width_px = int(page["render_width_px"]) * 2 + args.comparison_gap
            expected_height_px = int(page["render_height_px"])
            expected_width_pt = expected_width_px / 200 * 72
            expected_height_pt = expected_height_px / 200 * 72
            actual_width_pt, actual_height_pt = bilingual_pdf_sizes[idx]
            if abs(actual_width_pt - expected_width_pt) > 2 or abs(actual_height_pt - expected_height_pt) > 2:
                warnings.append(
                    f"Bilingual PDF page {int(page['page_number'])} size differs from expected comparison canvas "
                    f"{(round(expected_width_pt, 2), round(expected_height_pt, 2))} pt"
                )
                break

    result = {
        "ok": not errors,
        "prepared_page_count": len(pages),
        "translated_pdf_page_count": translated_pdf_count,
        "bilingual_pdf_page_count": bilingual_pdf_count,
        "errors": errors,
        "warnings": warnings,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
