#!/usr/bin/env python3
"""Build a bilingual comparison PDF with original and translated pages side by side."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageOps


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-image-dir", required=True, type=Path, help="Directory containing original page images")
    parser.add_argument("--translated-image-dir", required=True, type=Path, help="Directory containing normalized translated page images")
    parser.add_argument("--manifest", required=True, type=Path, help="Manifest generated by prepare_pdf_pages.py")
    parser.add_argument("--out", required=True, type=Path, help="Output bilingual PDF path")
    parser.add_argument("--dpi", type=int, default=200, help="PDF image resolution")
    parser.add_argument("--gap", type=int, default=24, help="Gap in pixels between original and translated pages")
    return parser.parse_args()


def load_manifest_pages(path: Path) -> list[dict]:
    payload = json.loads(path.expanduser().resolve().read_text(encoding="utf-8"))
    pages = payload.get("pages", [])
    if not pages:
        raise SystemExit(f"No pages found in manifest: {path}")
    return pages


def find_page_image(image_dir: Path, page_number: int) -> Path:
    expected = image_dir / f"page-{page_number:03d}.png"
    if expected.exists():
        return expected
    matches = sorted(image_dir.glob(f"page-{page_number:03d}.*"))
    matches = [path for path in matches if path.suffix.lower() in IMAGE_EXTENSIONS]
    if not matches:
        raise SystemExit(f"Missing page image for page {page_number}: {expected}")
    return matches[0]


def load_image(path: Path) -> Image.Image:
    return ImageOps.exif_transpose(Image.open(path)).convert("RGB")


def compose_page(left: Image.Image, right: Image.Image, target_size: tuple[int, int], gap: int) -> Image.Image:
    width, height = target_size
    canvas = Image.new("RGB", (width * 2 + gap, height), "white")

    left_fit = ImageOps.contain(left, (width, height), Image.Resampling.LANCZOS)
    right_fit = ImageOps.contain(right, (width, height), Image.Resampling.LANCZOS)

    left_offset = ((width - left_fit.width) // 2, (height - left_fit.height) // 2)
    right_offset = (width + gap + (width - right_fit.width) // 2, (height - right_fit.height) // 2)

    canvas.paste(left_fit, left_offset)
    canvas.paste(right_fit, right_offset)
    return canvas


def main() -> int:
    args = parse_args()
    if args.dpi < 72:
        raise SystemExit("--dpi must be at least 72")

    source_dir = args.source_image_dir.expanduser().resolve()
    translated_dir = args.translated_image_dir.expanduser().resolve()
    if not source_dir.exists():
        raise SystemExit(f"Source image directory not found: {source_dir}")
    if not translated_dir.exists():
        raise SystemExit(f"Translated image directory not found: {translated_dir}")

    manifest_pages = load_manifest_pages(args.manifest)
    pages = []
    for page in manifest_pages:
        page_number = int(page["page_number"])
        source = find_page_image(source_dir, page_number)
        translated = find_page_image(translated_dir, page_number)
        source_image = load_image(source)
        translated_image = load_image(translated)
        target_size = (int(page["render_width_px"]), int(page["render_height_px"]))
        pages.append(compose_page(source_image, translated_image, target_size, args.gap))

    if not pages:
        raise SystemExit("No pages to merge")

    out_path = args.out.expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    first, rest = pages[0], pages[1:]
    first.save(out_path, "PDF", resolution=args.dpi, save_all=True, append_images=rest)
    print(f"Merged {len(pages)} bilingual page(s) into {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
